{
 "title": "FIWARE GEs metrics: OpenMTC",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "OpenMTC: Catalogue Page Views",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.pageviews.catalogue",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: Academy Page Views",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.pageviews.academy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: ReadTheDocs Page Views",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.pageviews.rtd",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: Docker Pulls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.docker.pulls",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: GitHub Total Assets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.assets.total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: GitHub Download Assets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.assets.downloads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: GitHub Open Issues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.issues.open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: GitHub Closed Issues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.issues.closed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: GitHub Total Adopters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.adopters.total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: GitHub Open Issues from Adopters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.adopters.issues.open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: GitHub Closed Issues from Adopters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.adopters.issues.closed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: GitHub Commits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.commits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: Coveralls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.coveralls",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: Help-Desk tickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.helpdesk.tickets",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: Help-Desk Pending Tockets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "ge.helpdesk.pending",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: Help-Desk Mean Pending Tickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "d" }
   ],
   "targets": [
    {
     "measurement": "ge.helpdesk.days",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: GitHub Forks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.forks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: GitHub Watchers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.watchers",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  },
  {
   "title": "OpenMTC: GitHub Stars",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ge.gh.stars",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ge", "operator": "=", "value": "OpenMTC" }
     ]
    }
   ]
  }
 ]
}